matrix:
  include:
    - {osx_image: xcode9.4}
    - {osx_image: xcode10}
language: swift
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - xcodebuild -showBuildSettings -project conditionalCompilationOnXCVersion.xcodeproj -target conditionalCompilationOnXCVersion
  - xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c